language: objective-c
osx_image: xcode9.4
script:
 - set -o pipefail && xcodebuild -project NasaNotification.xcodeproj -scheme "NasaNotification" clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -destination "platform=macOS,arch=x86_64" | xcpretty
